### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by MasalaGianluca** [antonioCoco/SspiUacBypass#3]
Good job!!!

I am a security researcher and would be interested in asking you some questions:

Would this script work exclusively in a corporate LAN?

Could this script be an exploit in the wild?

Could this vulnerability apply in a Server scenario and not just a client scenario?

What degree of dangerousness would you give to this vulnerbaility? (LOW,MEDIUM;HIGH,CRITICAL)

Thank you very much and congratulations on your research.
Gianluca.

**Comment by antonioCoco** [comment]
Hi,

this PoC just demonstrates another (among many others) way of getting around UAC and it further demonstrates how broken its design is.
Sysadmins should never trust this boundary due to the fact neither MS trusts their own design.
The PoC works on default Windows installations (without any network requirements) and also on Servers. 
But on servers, UAC doesn't make that much sense as a concept in general.
